"""室内物品候选名。SigLIP2 用英文短语做零样本匹配，改这个元组即可。"""

ROOM_LABELS = (
    "person",
    "chair",
    "sofa",
    "stool",
    "bench",
    "table",
    "desk",
    "coffee table",
    "dining table",
    "bed",
    "pillow",
    "blanket",
    "nightstand",
    "dresser",
    "wardrobe",
    "shelf",
    "bookshelf",
    "cabinet",
    "drawer",
    "door",
    "window",
    "curtain",
    "rug",
    "lamp",
    "floor lamp",
    "ceiling light",
    "television",
    "monitor",
    "laptop",
    "keyboard",
    "computer mouse",
    "remote control",
    "mobile phone",
    "speaker",
    "headphones",
    "router",
    "refrigerator",
    "microwave",
    "oven",
    "stove",
    "sink",
    "faucet",
    "dishwasher",
    "washing machine",
    "air conditioner",
    "fan",
    "heater",
    "water dispenser",
    "coffee maker",
    "kettle",
    "cup",
    "mug",
    "bottle",
    "bowl",
    "plate",
    "pot",
    "trash can",
    "box",
    "bag",
    "backpack",
    "shoes",
    "clothes",
    "hanger",
    "towel",
    "mirror",
    "picture frame",
    "clock",
    "book",
    "plant",
    "vase",
    "toy",
    "cat",
    "dog",
    "toilet",
    "bathtub",
    "power strip",
    "cable",
    "charger",
)

PROMPTS = tuple(f"a photo of a {label}" for label in ROOM_LABELS)
